# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gizem/catkin_ws/src/hrc_training/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 767)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 541, 731))
        self.groupBox.setObjectName("groupBox")
        self.loggingcheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.loggingcheckBox.setGeometry(QtCore.QRect(40, 140, 151, 23))
        self.loggingcheckBox.setObjectName("loggingcheckBox")
        self.humanInitiateButton = QtWidgets.QPushButton(self.groupBox)
        self.humanInitiateButton.setGeometry(QtCore.QRect(40, 350, 151, 41))
        self.humanInitiateButton.setObjectName("humanInitiateButton")
        self.robotMoveButton = QtWidgets.QPushButton(self.groupBox)
        self.robotMoveButton.setGeometry(QtCore.QRect(40, 450, 151, 41))
        self.robotMoveButton.setObjectName("robotMoveButton")
        self.awindaButton = QtWidgets.QPushButton(self.groupBox)
        self.awindaButton.setGeometry(QtCore.QRect(40, 180, 151, 41))
        self.awindaButton.setObjectName("awindaButton")
        self.roscoreButton = QtWidgets.QPushButton(self.groupBox)
        self.roscoreButton.setGeometry(QtCore.QRect(40, 40, 151, 41))
        self.roscoreButton.setObjectName("roscoreButton")
        self.humanCalibrateButton = QtWidgets.QPushButton(self.groupBox)
        self.humanCalibrateButton.setGeometry(QtCore.QRect(40, 240, 151, 41))
        self.humanCalibrateButton.setObjectName("humanCalibrateButton")
        self.newUserButton = QtWidgets.QPushButton(self.groupBox)
        self.newUserButton.setGeometry(QtCore.QRect(290, 100, 89, 25))
        self.newUserButton.setObjectName("newUserButton")
        self.userRecordComboBox = QtWidgets.QComboBox(self.groupBox)
        self.userRecordComboBox.setGeometry(QtCore.QRect(40, 100, 221, 25))
        self.userRecordComboBox.setObjectName("userRecordComboBox")
        self.recordtextEdit = QtWidgets.QTextEdit(self.groupBox)
        self.recordtextEdit.setGeometry(QtCore.QRect(40, 500, 461, 171))
        self.recordtextEdit.setObjectName("recordtextEdit")
        self.roscorelineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.roscorelineEdit.setGeometry(QtCore.QRect(210, 50, 181, 25))
        self.roscorelineEdit.setObjectName("roscorelineEdit")
        self.awndalineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.awndalineEdit.setGeometry(QtCore.QRect(210, 190, 181, 25))
        self.awndalineEdit.setObjectName("awndalineEdit")
        self.humanCalibratelineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.humanCalibratelineEdit.setGeometry(QtCore.QRect(210, 240, 181, 25))
        self.humanCalibratelineEdit.setObjectName("humanCalibratelineEdit")
        self.humanInitiatelineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.humanInitiatelineEdit.setGeometry(QtCore.QRect(210, 360, 181, 25))
        self.humanInitiatelineEdit.setObjectName("humanInitiatelineEdit")
        self.emgLabel = QtWidgets.QLabel(self.groupBox)
        self.emgLabel.setGeometry(QtCore.QRect(240, 320, 41, 17))
        self.emgLabel.setObjectName("emgLabel")
        self.emglineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.emglineEdit.setGeometry(QtCore.QRect(210, 290, 181, 25))
        self.emglineEdit.setObjectName("emglineEdit")
        self.emgResetButton = QtWidgets.QPushButton(self.groupBox)
        self.emgResetButton.setGeometry(QtCore.QRect(280, 320, 89, 25))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.emgResetButton.setFont(font)
        self.emgResetButton.setObjectName("emgResetButton")
        self.robotInitiatelineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.robotInitiatelineEdit.setGeometry(QtCore.QRect(210, 460, 181, 25))
        self.robotInitiatelineEdit.setObjectName("robotInitiatelineEdit")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.groupBox)
        self.buttonBox.setGeometry(QtCore.QRect(130, 690, 166, 25))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gripperInitiateButton = QtWidgets.QPushButton(self.groupBox)
        self.gripperInitiateButton.setGeometry(QtCore.QRect(40, 400, 151, 41))
        self.gripperInitiateButton.setObjectName("gripperInitiateButton")
        self.gripperInitiatelineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.gripperInitiatelineEdit.setGeometry(QtCore.QRect(210, 410, 181, 25))
        self.gripperInitiatelineEdit.setObjectName("gripperInitiatelineEdit")
        self.mode1radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.mode1radioButton.setGeometry(QtCore.QRect(410, 130, 112, 23))
        self.mode1radioButton.setObjectName("mode1radioButton")
        self.mode2radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.mode2radioButton.setGeometry(QtCore.QRect(410, 160, 112, 23))
        self.mode2radioButton.setObjectName("mode2radioButton")
        self.humanJointResetButton = QtWidgets.QPushButton(self.groupBox)
        self.humanJointResetButton.setGeometry(QtCore.QRect(40, 290, 151, 25))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.humanJointResetButton.setFont(font)
        self.humanJointResetButton.setObjectName("humanJointResetButton")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(200, 270, 201, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        self.frame_2.setGeometry(QtCore.QRect(30, 230, 171, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.raise_()
        self.loggingcheckBox.raise_()
        self.humanInitiateButton.raise_()
        self.robotMoveButton.raise_()
        self.awindaButton.raise_()
        self.roscoreButton.raise_()
        self.newUserButton.raise_()
        self.userRecordComboBox.raise_()
        self.recordtextEdit.raise_()
        self.roscorelineEdit.raise_()
        self.awndalineEdit.raise_()
        self.humanCalibratelineEdit.raise_()
        self.humanInitiatelineEdit.raise_()
        self.emgLabel.raise_()
        self.emglineEdit.raise_()
        self.emgResetButton.raise_()
        self.robotInitiatelineEdit.raise_()
        self.buttonBox.raise_()
        self.gripperInitiateButton.raise_()
        self.gripperInitiatelineEdit.raise_()
        self.mode1radioButton.raise_()
        self.mode2radioButton.raise_()
        self.frame.raise_()
        self.humanCalibrateButton.raise_()
        self.humanJointResetButton.raise_()
        self.plotgroupBox = QtWidgets.QGroupBox(Form)
        self.plotgroupBox.setGeometry(QtCore.QRect(570, 20, 401, 731))
        self.plotgroupBox.setObjectName("plotgroupBox")
        self.selectUserButton = QtWidgets.QPushButton(self.plotgroupBox)
        self.selectUserButton.setGeometry(QtCore.QRect(280, 50, 89, 25))
        self.selectUserButton.setObjectName("selectUserButton")
        self.userSelectComboBox = QtWidgets.QComboBox(self.plotgroupBox)
        self.userSelectComboBox.setGeometry(QtCore.QRect(50, 50, 221, 25))
        self.userSelectComboBox.setObjectName("userSelectComboBox")
        self.userLabel = QtWidgets.QLabel(self.plotgroupBox)
        self.userLabel.setGeometry(QtCore.QRect(10, 50, 67, 17))
        self.userLabel.setObjectName("userLabel")
        self.plottextEdit = QtWidgets.QTextEdit(self.plotgroupBox)
        self.plottextEdit.setGeometry(QtCore.QRect(0, 130, 401, 201))
        self.plottextEdit.setObjectName("plottextEdit")
        self.plotpushButton = QtWidgets.QPushButton(self.plotgroupBox)
        self.plotpushButton.setGeometry(QtCore.QRect(150, 350, 89, 25))
        self.plotpushButton.setObjectName("plotpushButton")
        self.label = QtWidgets.QLabel(self.plotgroupBox)
        self.label.setGeometry(QtCore.QRect(140, 580, 141, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/home/gizem/catkin_ws/src/hrc_training/ui/../fig/hvlLogo_original.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Record"))
        self.loggingcheckBox.setText(_translate("Form", "Logging Disabled"))
        self.humanInitiateButton.setText(_translate("Form", "Human Initiate"))
        self.robotMoveButton.setText(_translate("Form", "Robot Move"))
        self.awindaButton.setText(_translate("Form", "awindamonitor"))
        self.roscoreButton.setText(_translate("Form", "roscore"))
        self.humanCalibrateButton.setText(_translate("Form", "Human Calibrate"))
        self.newUserButton.setText(_translate("Form", "New User"))
        self.emgLabel.setText(_translate("Form", "EMG:"))
        self.emgResetButton.setText(_translate("Form", "EMG Reset"))
        self.gripperInitiateButton.setText(_translate("Form", "Gripper Initiate"))
        self.mode1radioButton.setText(_translate("Form", "Mode-1"))
        self.mode2radioButton.setText(_translate("Form", "Mode-2"))
        self.humanJointResetButton.setText(_translate("Form", "Human Joint Reset"))
        self.plotgroupBox.setTitle(_translate("Form", "Plot"))
        self.selectUserButton.setText(_translate("Form", "Select User"))
        self.userLabel.setText(_translate("Form", "User:"))
        self.plotpushButton.setText(_translate("Form", "PLOT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
