# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gizem/catkin_ws/src/hrc_training/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 767)
        self.recordgroupBox = QtWidgets.QGroupBox(Form)
        self.recordgroupBox.setGeometry(QtCore.QRect(20, 20, 541, 731))
        self.recordgroupBox.setObjectName("recordgroupBox")
        self.loggingcheckBox = QtWidgets.QCheckBox(self.recordgroupBox)
        self.loggingcheckBox.setGeometry(QtCore.QRect(40, 140, 151, 23))
        self.loggingcheckBox.setObjectName("loggingcheckBox")
        self.humanInitiateButton = QtWidgets.QPushButton(self.recordgroupBox)
        self.humanInitiateButton.setGeometry(QtCore.QRect(200, 360, 151, 41))
        self.humanInitiateButton.setObjectName("humanInitiateButton")
        self.robotMoveButton = QtWidgets.QPushButton(self.recordgroupBox)
        self.robotMoveButton.setGeometry(QtCore.QRect(200, 440, 151, 41))
        self.robotMoveButton.setObjectName("robotMoveButton")
        self.awindaButton = QtWidgets.QPushButton(self.recordgroupBox)
        self.awindaButton.setGeometry(QtCore.QRect(240, 40, 151, 41))
        self.awindaButton.setObjectName("awindaButton")
        self.roscoreButton = QtWidgets.QPushButton(self.recordgroupBox)
        self.roscoreButton.setGeometry(QtCore.QRect(40, 40, 151, 41))
        self.roscoreButton.setObjectName("roscoreButton")
        self.newUserButton = QtWidgets.QPushButton(self.recordgroupBox)
        self.newUserButton.setGeometry(QtCore.QRect(290, 100, 89, 25))
        self.newUserButton.setObjectName("newUserButton")
        self.userRecordComboBox = QtWidgets.QComboBox(self.recordgroupBox)
        self.userRecordComboBox.setGeometry(QtCore.QRect(40, 100, 221, 25))
        self.userRecordComboBox.setObjectName("userRecordComboBox")
        self.recordtextEdit = QtWidgets.QTextEdit(self.recordgroupBox)
        self.recordtextEdit.setGeometry(QtCore.QRect(40, 500, 461, 171))
        self.recordtextEdit.setObjectName("recordtextEdit")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.recordgroupBox)
        self.buttonBox.setGeometry(QtCore.QRect(200, 690, 166, 25))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gripperInitiateButton = QtWidgets.QPushButton(self.recordgroupBox)
        self.gripperInitiateButton.setGeometry(QtCore.QRect(200, 400, 151, 41))
        self.gripperInitiateButton.setObjectName("gripperInitiateButton")
        self.mode1radioButton = QtWidgets.QRadioButton(self.recordgroupBox)
        self.mode1radioButton.setGeometry(QtCore.QRect(410, 130, 112, 23))
        self.mode1radioButton.setObjectName("mode1radioButton")
        self.mode2radioButton = QtWidgets.QRadioButton(self.recordgroupBox)
        self.mode2radioButton.setGeometry(QtCore.QRect(410, 160, 112, 23))
        self.mode2radioButton.setObjectName("mode2radioButton")
        self.emg_frame = QtWidgets.QFrame(self.recordgroupBox)
        self.emg_frame.setGeometry(QtCore.QRect(290, 190, 211, 161))
        self.emg_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.emg_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.emg_frame.setObjectName("emg_frame")
        self.emgResetButton = QtWidgets.QPushButton(self.emg_frame)
        self.emgResetButton.setGeometry(QtCore.QRect(50, 130, 89, 25))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.emgResetButton.setFont(font)
        self.emgResetButton.setObjectName("emgResetButton")
        self.emgCurrentLabel = QtWidgets.QLabel(self.emg_frame)
        self.emgCurrentLabel.setGeometry(QtCore.QRect(20, 80, 101, 17))
        self.emgCurrentLabel.setObjectName("emgCurrentLabel")
        self.emgTresholdLabel = QtWidgets.QLabel(self.emg_frame)
        self.emgTresholdLabel.setGeometry(QtCore.QRect(20, 40, 101, 17))
        self.emgTresholdLabel.setObjectName("emgTresholdLabel")
        self.emgTresholdLineEdit = QtWidgets.QLineEdit(self.emg_frame)
        self.emgTresholdLineEdit.setGeometry(QtCore.QRect(120, 30, 81, 25))
        self.emgTresholdLineEdit.setObjectName("emgTresholdLineEdit")
        self.emgCurrentLineEdit = QtWidgets.QLineEdit(self.emg_frame)
        self.emgCurrentLineEdit.setGeometry(QtCore.QRect(120, 80, 81, 25))
        self.emgCurrentLineEdit.setObjectName("emgCurrentLineEdit")
        self.joint_frame = QtWidgets.QFrame(self.recordgroupBox)
        self.joint_frame.setGeometry(QtCore.QRect(30, 190, 221, 161))
        self.joint_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joint_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joint_frame.setObjectName("joint_frame")
        self.elbowTresholdLineEdit = QtWidgets.QLineEdit(self.joint_frame)
        self.elbowTresholdLineEdit.setGeometry(QtCore.QRect(130, 30, 81, 25))
        self.elbowTresholdLineEdit.setObjectName("elbowTresholdLineEdit")
        self.elbowTresholdLabel = QtWidgets.QLabel(self.joint_frame)
        self.elbowTresholdLabel.setGeometry(QtCore.QRect(10, 30, 111, 17))
        self.elbowTresholdLabel.setObjectName("elbowTresholdLabel")
        self.humanCalibrateButton = QtWidgets.QPushButton(self.joint_frame)
        self.humanCalibrateButton.setGeometry(QtCore.QRect(40, 80, 151, 41))
        self.humanCalibrateButton.setObjectName("humanCalibrateButton")
        self.humanJointResetButton = QtWidgets.QPushButton(self.joint_frame)
        self.humanJointResetButton.setGeometry(QtCore.QRect(40, 130, 151, 25))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        self.humanJointResetButton.setFont(font)
        self.humanJointResetButton.setObjectName("humanJointResetButton")
        self.emg_frame.raise_()
        self.joint_frame.raise_()
        self.loggingcheckBox.raise_()
        self.humanInitiateButton.raise_()
        self.robotMoveButton.raise_()
        self.awindaButton.raise_()
        self.roscoreButton.raise_()
        self.newUserButton.raise_()
        self.userRecordComboBox.raise_()
        self.recordtextEdit.raise_()
        self.buttonBox.raise_()
        self.gripperInitiateButton.raise_()
        self.mode1radioButton.raise_()
        self.mode2radioButton.raise_()
        self.plotgroupBox = QtWidgets.QGroupBox(Form)
        self.plotgroupBox.setGeometry(QtCore.QRect(570, 20, 401, 731))
        self.plotgroupBox.setObjectName("plotgroupBox")
        self.selectUserButton = QtWidgets.QPushButton(self.plotgroupBox)
        self.selectUserButton.setGeometry(QtCore.QRect(280, 50, 89, 25))
        self.selectUserButton.setObjectName("selectUserButton")
        self.userSelectComboBox = QtWidgets.QComboBox(self.plotgroupBox)
        self.userSelectComboBox.setGeometry(QtCore.QRect(50, 50, 221, 25))
        self.userSelectComboBox.setObjectName("userSelectComboBox")
        self.userLabel = QtWidgets.QLabel(self.plotgroupBox)
        self.userLabel.setGeometry(QtCore.QRect(10, 50, 67, 17))
        self.userLabel.setObjectName("userLabel")
        self.plottextEdit = QtWidgets.QTextEdit(self.plotgroupBox)
        self.plottextEdit.setGeometry(QtCore.QRect(0, 130, 401, 201))
        self.plottextEdit.setObjectName("plottextEdit")
        self.plotpushButton = QtWidgets.QPushButton(self.plotgroupBox)
        self.plotpushButton.setGeometry(QtCore.QRect(150, 350, 89, 25))
        self.plotpushButton.setObjectName("plotpushButton")
        self.label = QtWidgets.QLabel(self.plotgroupBox)
        self.label.setGeometry(QtCore.QRect(140, 580, 141, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/home/gizem/catkin_ws/src/hrc_training/ui/../fig/hvlLogo_original.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.recordgroupBox.setTitle(_translate("Form", "Record"))
        self.loggingcheckBox.setText(_translate("Form", "Logging Disabled"))
        self.humanInitiateButton.setText(_translate("Form", "Human Initiate"))
        self.robotMoveButton.setText(_translate("Form", "Robot Move"))
        self.awindaButton.setText(_translate("Form", "awindamonitor"))
        self.roscoreButton.setText(_translate("Form", "roscore"))
        self.newUserButton.setText(_translate("Form", "New User"))
        self.gripperInitiateButton.setText(_translate("Form", "Gripper Initiate"))
        self.mode1radioButton.setText(_translate("Form", "Mode-1"))
        self.mode2radioButton.setText(_translate("Form", "Mode-2"))
        self.emgResetButton.setText(_translate("Form", "EMG Reset"))
        self.emgCurrentLabel.setText(_translate("Form", "EMG current:"))
        self.emgTresholdLabel.setText(_translate("Form", "EMG treshold:"))
        self.elbowTresholdLabel.setText(_translate("Form", "Elbow treshold:"))
        self.humanCalibrateButton.setText(_translate("Form", "Human Calibrate"))
        self.humanJointResetButton.setText(_translate("Form", "Human Joint Reset"))
        self.plotgroupBox.setTitle(_translate("Form", "Plot"))
        self.selectUserButton.setText(_translate("Form", "Select User"))
        self.userLabel.setText(_translate("Form", "User:"))
        self.plotpushButton.setText(_translate("Form", "PLOT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
